[package]
name = "xbpf"
version = "0.0.3"
edition = "2024"
description.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
glob = { version = "0.3.4", optional = true }
libbpf-cargo = "0.27.0"
libbpf-rs = "0.27.0"
tokio = { version = "1.53.1", features = ["sync"], optional = true }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"], optional = true }

[dev-dependencies]
temp-env = "0.3.6"
tempfile = "3.27.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[features]
default = ["build", "tracing"]
build = ["dep:glob", "dep:tracing-subscriber"]
collections = ["dep:tokio"]
tracing = ["collections"]
tracing-source-loc = []
