[package]
name = "example"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.104"
xbpf = { path = "../xbpf", features = ["tracing-source-loc"]  }
libbpf-rs = "0.27.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
xbpf = { path = "../xbpf", features = ["tracing-source-loc"] }

[dev-dependencies]
xbpf = { path = "../xbpf", features = ["test"] }
