//! Loading of eBPF programs from a generated skeleton.
use crate::{
    OpenObject,
    libbpf_rs::{
        Result,
        skel::{OpenSkel, Skel, SkelBuilder},
    },
};
use std::marker::PhantomData;

/// An eBPF program that is loaded into the kernel.
///
/// This is what a skeleton generated by [`crate::build()`] turns into once it has
/// been opened and loaded. The type parameters follow the three stages libbpf
/// models: the builder `SB`, the opened skeleton `OS`, and the loaded skeleton
/// `S` that the program hands out through [`Program::skel`].
///
/// The program is loaded but not attached. Attaching is left to the caller,
/// since it decides which hooks to install and has to hold on to the resulting
/// links for as long as they should stay attached.
///
/// See the [crate-level documentation](crate) for a complete example.
pub struct Program<
    'obj,
    SB: SkelBuilder<'obj, Output = OS>,
    OS: OpenSkel<'obj, Output = S>,
    S: Skel<'obj>,
> {
    obj_marker: PhantomData<&'obj ()>,
    sb_marker: PhantomData<SB>,
    os_marker: PhantomData<OS>,

    /// The loaded skeleton, granting access to the maps and programs of the
    /// eBPF object.
    pub skel: S,
}

impl<'obj, SB: SkelBuilder<'obj, Output = OS>, OS: OpenSkel<'obj, Output = S>, S: Skel<'obj>>
    Program<'obj, SB, OS, S>
{
    /// Opens `builder` into `obj` and loads the resulting skeleton into the
    /// kernel.
    ///
    /// `obj` holds the eBPF object the skeleton is opened into and therefore
    /// has to outlive the returned program.
    ///
    /// With the `tracing` feature this also hands the object to
    /// [`crate::tracing::try_init`], so that whatever the program traces is
    /// emitted as [`tracing`] events.
    ///
    /// # Errors
    ///
    /// Returns an error if the object cannot be opened or if the verifier
    /// rejects one of its programs. With the `tracing` feature it also returns
    /// an error if the object has no `bpf_tracing_events` ring buffer, which is
    /// the case for programs that don't include `xbpf.h`. Load those with
    /// [`crate::libbpf_rs::ObjectBuilder`] instead.
    ///
    /// [`tracing`]: https://github.com/tokio-rs/tracing
    pub fn build(builder: SB, obj: &'obj mut OpenObject) -> Result<Program<'obj, SB, OS, S>> {
        let open_skel = builder.open(obj)?;
        let skel = open_skel.load()?;

        let prog = Program {
            obj_marker: PhantomData,
            sb_marker: PhantomData,
            os_marker: PhantomData,
            skel,
        };

        #[cfg(feature = "tracing")]
        crate::tracing::try_init(prog.skel.object())?;

        Ok(prog)
    }
}
