[workspace]
resolver = "2"
members = ["xbpf", "example"]

[workspace.package]
license = "MIT"
authors = [
    "lerboe <mail@laurinbrandner.ch>",
]
repository = "https://github.com/lerboe/bpf"
readme = "README.md"
keywords = ["ebpf", "bpf", "libbpf", "linux"]
description = "An ergonomic and light-weight eBPF library"
categories = ["network-programming"]
